---
- name: install packages
  pkgng: name={{ item }} state=present
  with_items:
    - py27-virtualenv
    - rsync
    - sudo
    - libxslt
    - ca_root_nss

- name: activate root certificates
  file:
    state: link
    src: /usr/local/share/certs/ca-root-nss.crt
    force: yes
    owner: root
    path: /etc/ssl/cert.pem

- name: create application user
  user: name={{watchdog_app_user}}

- name: ensure application directory
  file: path={{watchdog_app_dir}} state=directory owner={{watchdog_app_user}} mode=770

- name: ensure log directory
  file: path={{watchdog_app_dir}}/var state=directory owner={{watchdog_app_user}} mode=770

- name: ensure upload directory
  file: path={{watchdog_app_dir}}/upload state=directory owner={{watchdog_app_user}} mode=770

- name: init virtualenv in application directory
  sudo: yes
  sudo_user: "{{watchdog_app_user}}"
  command: virtualenv --system-site-packages . chdir={{watchdog_app_dir}} creates={{watchdog_app_dir}}/bin/python

- name: upload requirements
  copy:
    src: requirements.txt
    dest: "{{watchdog_app_dir}}"
    owner: "root"
    group: "wheel"
    mode: "775"

- name: install requirements
  pip:
    requirements: "{{watchdog_app_dir}}/requirements.txt"
    virtualenv: "{{watchdog_app_dir}}"

- name: upload watchdog configuration
  template:
    src: watchdog.ini
    dest: "{{watchdog_app_dir}}"
    owner: "root"
    group: "wheel"
    mode: "775"

- name: install cronjob to run watchdog automatically
  cron:
    name: "briefkasten watchdog"
    special_time: "hourly"
    user: "{{watchdog_app_user}}"
    job: "{{watchdog_app_dir}}/bin/watchdog {{watchdog_app_dir}}/watchdog.ini"

