---
- name: install packages
  pkgng:
    name: "{{ item }}"
    state: present
    cached: yes
  with_items:
    - py312-supervisor
    - py312-virtualenv
    - rsync
    - libxslt
    - sudo
    - gnupg
    - uv

- name: create application user
  # this creates /home/pyramid/.ssh/id_rsa{.pub}
  user:
    name: "{{appuser}}"
    uid: "{{appuserid}}"
    createhome: yes
    generate_ssh_key: yes

- name: ensure application directory
  file:
    path: "{{apphome}}"
    state: directory
    owner: "{{appuser}}"
    mode: "775"

- name: upload requirements
  copy:
    src: "../../../../application/{{item}}"
    dest: "{{apphome}}/"
    owner: "root"
    mode: "644"
  with_items:
    - pyproject.toml
    - uv.lock
  tags: update-briefkasten

- name: install python eggs
  command: "uv sync --frozen --no-install-project"
  args:
    chdir: "{{apphome}}"
  tags: update-briefkasten

- name: install briefkasten
  command: "uv pip install --no-deps briefkasten"
  args:
    chdir: "{{apphome}}"
  tags: update-briefkasten

- name: symlink `bin/` directory
  file:
    src: "{{apphome}}/.venv/bin"
    dest: "{{apphome}}/bin"
    state: link
  tags: update-briefkasten
