[tox]
envlist = py3

[testenv]
setenv =
    SYSTEM_VERSION_COMPAT = 0
    UV_FROZEN = true
    UV_PROJECT_ENVIRONMENT={work_dir}/{env_name}
allowlist_externals =
    uv
commands =
    uv run py.test {posargs} {toxinidir}/briefkasten/tests

[testenv:develop]
basepython = python3
envdir = venv/
changedir = .
usedevelop = True
deps =
    Babel
    devpi-client
    pdbpp
    pyramid_debugtoolbar
    repoze.sphinx.autointerface
    Sphinx
commands =
    pip install -e .
