version: 2
updates:
- package-ecosystem: "pip"
  directory: "/application"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "MAINT:"
  labels:
  - "dependencies"
  - "team-zoe"
- package-ecosystem: "pip"
  directory: "/watchdog"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "MAINT:"
  labels:
  - "dependencies"
  - "team-zoe"
- package-ecosystem: "pip"
  directory: "/deployment/roles/briefkasten/files"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "MAINT:"
  labels:
  - "dependencies"
  - "team-zoe"
