# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-yaml
    args:
    - "--allow-multiple-documents"
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: '3.2.1'
  hooks:
  - id: editorconfig-checker
    alias: ec
- repo: https://github.com/pycqa/flake8
  rev: '7.3.0'
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-awesome
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-debugger
    - flake8-deprecated
    - flake8-fixme
    - flake8-pep3101
    - flake8-polyfill
    - flake8-print
    - flake8-noqa
    args:
    - "--max-line-length=132"
    - "--ignore=I001,I003,I005,I900,C408,PT013,R504,S001,S101,T101,T201"
    - "--per-file-ignores=
      appserver.py:E800,S108
      commands.py:A004
      conf.py:A001,E265,E800
      debug_ttw.py:E800
      dropbox.py:R503,R505,S103,S404,S602,S701
      housekeeping.py:IF100
      jailhost.py:E800
      notifications.py:N802
      */briefkasten/testing.py:S701,T102
      */briefkasten/tests/test_*.py:S105,S106,S324,ECE001
      */briefkasten_watchdog/__init__.py:G001,G004,G200,N802"
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: ["--verbose"]
