INHERIT: /zon/common_config.yaml
nav:
- README.md
- Deployment:
  - deployment/index.md
  - deployment/monitoring.md
- Application:
  - application/develop.md
  - application/workings.md
  - application/i18n.md
repo_url: https://github.com/ZeitOnline/briefkasten
site_name: briefkasten
team: team-engagement
