---
- hosts: briefkasten
  user: root
  tasks:
    - name: ensure jails are running
      command: "ezjail-admin start {{item}}"
      args:
        creates: "/usr/jails/{{item}}"
      with_items:
      - worker
      - webserver
      - appserver
      - cleanser
      tags: jails

- hosts: briefkasten-webserver
  user: root
  roles:
    - { role: common, tags: ['common', 'webserver'] }
    - { role: webserver, tags: ['webserver'] }

- hosts: briefkasten-worker
  user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: briefkasten, tags: ['briefkasten'] }
    - { role: supervisord, tags: ['supervisord'] }
    - { role: worker, tags: ['worker'] }

- hosts: briefkasten-appserver
  user: root
  roles:
    - { role: common, tags: ['common', 'appserver'] }
    - { role: briefkasten, tags: ['briefkasten'] }
    - { role: supervisord, tags: ['supervisord'] }
    - { role: appserver, tags: ['appserver'] }

- hosts: briefkasten-cleanser
  user: root
  tasks:
    - name: install packages
      pkgng:
        name: "{{ item }}"
        state: present
      with_items:
      - zip
      - netpbm
      - ghostscript10
      - libreoffice
    - name: create cleanser user
      user:
        name: cleanser
        createhome: yes
    - name: create cleanser .ssh
      file:
        path: /home/cleanser/.ssh
        owner: cleanser
        mode: "700"
        state: directory

- hosts: briefkasten
  user: root
  tasks:
    - name: install jaildaemon
      pkgng:
        name: jaildaemon
        state: present
    - name: enable jaildaemon
      service:
        name: jaildaemon
        enabled: true
        state: started
      tags: cleanser_clones
    # grant worker's pyramid user ssh access
    - name: copy keyfile
      command: cp {{ jails_dir }}/worker/home/pyramid/.ssh/id_rsa.pub {{ jails_dir }}/cleanser/home/cleanser/.ssh/authorized_keys
      args:
        creates: "{{ jails_dir }}/cleanser/home/cleanser/.ssh/authorized_keys"
      tags: cleanser_clones
    - name: fix permissions on keyfile
      command: chmod 600 {{ jails_dir }}/cleanser/home/cleanser/.ssh/authorized_keys
      tags: cleanser_clones
    - name: read ssh pub host key
      shell: sed -E -e 's:[^ ]+$::' {{ jails_dir }}/cleanser/etc/ssh/ssh_host_rsa_key.pub
      register: cleanser_ssh_fingerprint
      tags: cleanser_clones
    - name: configure known_hosts for cleanser jails
      template:
        src: templates/worker_known_hosts
        dest: "{{ jails_dir }}/worker/home/{{appuser}}/.ssh/known_hosts"
        owner: "{{appuserid}}"
        mode: "0600"
      tags: cleanser_clones

- hosts: briefkasten-worker
  user: root
  tasks:
    - name: fix ownership of known_hosts
      command: chown pyramid /home/pyramid/.ssh/known_hosts
      tags: cleanser_clones

- hosts: briefkasten-cleanser
  user: root
  tasks:
    - name: ensure ownership of scripts
      command: chown -R cleanser /home/cleanser
      tags: cleanser_clones
    - name: Upload cleanser scripts
      copy:
        src: ../application/middleware_scripts/
        dest: /usr/local/bin/
        mode: '0755'
      tags: cleanser_clones

# the cleanser jail is now ready to be snapshotted and cloned
- hosts: briefkasten
  user: root
  tasks:
    - name: create cleanser snapshot
      command: "zfs snapshot tank/jails/cleanser@clonesource"
      args:
        creates: "/usr/jails/cleanser/.zfs/snapshot/clonesource"
      tags: cleanser_clones
    - name: create cleanser clones (from snapshot)
      command: "zfs clone tank/jails/cleanser@clonesource tank/jails/cleanser_{{item}}"
      args:
        creates: "/usr/jails/cleanser_{{item}}"
      with_sequence: start=1 end="{{ploy_cleanser_count}}" format="%02d"
      tags: cleanser_clones
    - name: configure sshd for cleansers
      template:
        src: templates/cleanser_sshd_config
        owner: root
        group: wheel
        mode: "0600"
        dest: "/usr/jails/cleanser_{{item}}/etc/ssh/sshd_config"
      with_sequence: start=1 end="{{ploy_cleanser_count}}" format="%02d"
      tags: cleanser_clones
    - name: configure clones for ezjail
      command: "ezjail-admin create -x cleanser_{{item}} {{hostvars['briefkasten-cleanser']['ploy_ip']}}"
      args:
        creates: "/usr/local/etc/ezjail/cleanser_{{item}}"
      with_sequence: start=1 end="{{ploy_cleanser_count}}" format="%02d"
      tags: cleanser_clones
    - name: create rollback snapshot from each clone (jdispatch_rollback)
      command: "zfs snapshot tank/jails/cleanser_{{item}}@jdispatch_rollback"
      args:
        creates: "/usr/jails/cleanser_{{item}}/.zfs/snapshot/jdispatch_rollback"
      with_sequence: start=1 end="{{ploy_cleanser_count}}" format="%02d"
      tags: cleanser_clones
    - name: install jdispatch tool
      copy:
        src: files/jdispatch.sh
        dest: /usr/local/bin/jdispatch
        owner: root
        group: wheel
        mode: "0755"
      tags:
      - cleanser_clones
      - jdispatch
    - name: configure jdispatch tool
      template:
        src: templates/jdispatch.conf
        dest: /usr/local/etc/
        owner: root
        group: wheel
        mode: "0644"
      with_sequence: start=1 end="{{ploy_cleanser_count}}" format="%02d"
      tags: cleanser_clones
    - name: install jdispatcher rc script
      copy:
        src: files/jdispatch.rc
        dest: /usr/local/etc/rc.d/jdispatch
        mode: "0755"
        owner: root
        group: wheel
      tags:
      - jdispatch
    - name: make sure jdispatch tool is running and enabled
      service:
        name: jdispatch
        state: started
        enabled: true
      tags:
      - jdispatch
    - name: enable cronjob for jdispatch (as 'reaper')
      cron:
        name: "make sure long-running cleanser jails are reaped"
        job: "/usr/local/bin/jdispatch"
        minute: "*/3"
      tags:
      - jdispatch
  roles:
    - role: zabbix-agent
      when: ploy_enable_zabbix == "true"
      tags:
      - zabbix-agent
