[project]
name = "briefkasten-deployment"
version = "0.4.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ansible",
    "ansible-core<2.15",
    "bsdploy",
    "keyring",
    "ploy",
    "ploy-ansible",
    "ploy-ec2",
    "setuptools<82",
]

[tool.uv.sources]
bsdploy = { git = "https://github.com/witsch/bsdploy.git", rev = "use-extra-zfs-properties" }
ploy = { git = "https://github.com/witsch/ploy.git", rev = "python-3.12-fixes" }
ploy-ansible = { git = "https://github.com/ployground/ploy_ansible.git", rev = "d8e54684989ccbdd5ba5aa7c0a4eaa20c9cc3176" }

[tool.ruff]
line-length = 92
target-version = "py314"


[tool.ruff.lint]
select = ["A", "B", "C4", "E", "EXE", "F", "FIX", "G", "PT", "S", "T10", "T20", "UP"]

[tool.ruff.lint.per-file-ignores]
"appserver.py" = ["S108"]

[dependency-groups]
lint = [
    "editorconfig-checker>=3.6.1",
    "lefthook>=2.1.10",
    "ruff>=0.15.22",
    "yamllint>=1.38.0",
]
