---

- name: install acme.sh
  pkgng:
    name: "{{item}}"
    state: present
    cached: yes
  with_items:
    - "acme.sh"
    - "bind-tools"
    - "sudo"

- name: configure acme secret
  template:
    src: ddns.key
    dest: /var/db/acme/ddns.key

- name: configure acme setup
  template:
    src: account.conf
    dest: /var/db/acme/.acme.sh/account.conf

- name: configure log access
  file:
    dest: /var/log/acme.sh.log
    owner: acme
    state: touch

- name: request initial certificate (this may take a while)
  command: "sudo -u acme /usr/local/sbin/acme.sh --issue --dns dns_nsupdate --dnssleep 5 -d {{ploy_fqdn}} --domain-alias {{ploy_acme_domain}}"
  args:
    chdir: /var/db/acme
    creates: "/var/db/acme/certs/{{ploy_fqdn}}/fullchain.cer"

- name: upload nginx reload script
  copy:
    src: reload-nginx.sh
    dest: "/usr/local/bin/reload-nginx"
    owner: root
    group: wheel
    mode: "6555"

- name: ensure certs directory exists
  file:
    path: /usr/local/etc/nginx/certs
    state: directory
    owner: acme
    group: wheel
    mode: "0775"

- name: let acme user reload nginx
  copy:
    src: acme
    dest: /usr/local/etc/sudoers.d/acme
    owner: root
    group: wheel
    mode: "644"
    validate: "visudo -cf %s"

- name: install certificate
  command: "sudo -u acme /usr/local/sbin/acme.sh --install-cert -d {{ploy_fqdn}} --key-file /usr/local/etc/nginx/certs/briefkasten.key --fullchain-file /usr/local/etc/nginx/certs/briefkasten.crt --reloadcmd 'sudo /usr/local/bin/reload-nginx'"
  args:
    creates: /usr/local/etc/nginx/briefkasten.key

- name: install cronjob to run check and renew sites automatically
  copy:
    src: acme_crontab
    dest: /var/cron/tabs/acme
    owner: root
    group: wheel
    mode: "600"
  notify: restart cron
