---
- name: install packages
  pkgng:
    name: "{{ item }}"
    state: present
    cached: yes
  with_items:
    - nginx

- name: configure nginx
  template:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf

- { include: ssl.yml }

- name: make sure nginx is running or reloaded
  service:
    name: nginx
    state: started
    enabled: true

- { include: acme.yml, tags: acme, when: "{{ ploy_use_acme }}" }
