---
- name: install packages
  pkgng:
    name: "{{ item }}"
    state: present
    cached: yes
  with_items:
    - nginx

- { include: ssl.yml, when: "not {{ ploy_use_acme }}" }
- { include: acme.yml, tags: acme, when: "{{ ploy_use_acme }}" }

- name: make sure nginx is running or reloaded
  service:
    name: nginx
    state: started
    enabled: true
