[tox]
envlist = py3

[testenv]
setenv =
    SYSTEM_VERSION_COMPAT = 0
    UV_FROZEN = true
    UV_PROJECT_ENVIRONMENT={work_dir}/{env_name}
allowlist_externals =
    uv
changedir = {toxinidir}/src/watchdog/
commands =
    uv run py.test {posargs} {toxinidir}/src/watchdog

[testenv:develop]
basepython = python3
envdir = venv/
changedir = {toxinidir}/src/watchdog
usedevelop = True
commands =
    pip install -e .
