name: Test backend
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/backend-tests.yaml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'testing.yaml'
      - 'application/briefkasten/**'
      - 'application/Pipfile**'
      - 'application/pyproject.toml'
      - 'application/requirements.txt'
      - 'application/setup.*'
      - 'application/tox.ini'
jobs:
  build:
    uses: zeitonline/gh-action-workflows/.github/workflows/build-test-push.yaml@d0c1b354a122f39a58bdb7d1cfa87ae3c0aa7532 # 3.0.2
