name: Backend CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
concurrency:
  group: backend
  cancel-in-progress: true
jobs:
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/lefthook.yaml@89c86adf124007d97fae113c3e0c176e9c8391c6 # 4.1.0
  # run 'release-please' first
  release-please:
    needs: linter
    uses: zeitonline/gh-action-workflows/.github/workflows/release-please.yaml@89c86adf124007d97fae113c3e0c176e9c8391c6 # 4.1.0
    secrets: inherit
  # without release: run tests
  build:
    needs: release-please
    if: ${{ ! needs.release-please.outputs.release_created }}
    uses: zeitonline/gh-action-workflows/.github/workflows/build-test-push.yaml@89c86adf124007d97fae113c3e0c176e9c8391c6 # 4.1.0
    secrets: inherit
  # with release: notify
  notify:
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: zeitonline/gh-action-workflows/.github/workflows/release-notification.yaml@89c86adf124007d97fae113c3e0c176e9c8391c6 # 4.1.0
    secrets: inherit
    with:
      environment: production
      version: ${{ needs.release-please.outputs.tag_name }}
      emoji: mailbox
