name: Backend CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
concurrency:
  group: backend
  cancel-in-progress: true
jobs:
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/lefthook.yaml@0e9360ebe8baf323a1bfd03567237f05bfb239df # 3.0.0
  # run 'release-please' first
  release-please:
    needs: linter
    uses: zeitonline/gh-action-workflows/.github/workflows/release-please.yaml@0e9360ebe8baf323a1bfd03567237f05bfb239df # 3.0.0
    secrets: inherit
  # without release: run tests
  build:
    needs: release-please
    if: ${{ ! needs.release-please.outputs.release_created }}
    uses: zeitonline/gh-action-workflows/.github/workflows/build-test-push.yaml@0e9360ebe8baf323a1bfd03567237f05bfb239df # 3.0.0
    secrets: inherit
  # with release: notify
  notify:
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: zeitonline/gh-action-workflows/.github/workflows/release-notification.yaml@0e9360ebe8baf323a1bfd03567237f05bfb239df # 3.0.0
    secrets: inherit
    with:
      environment: production
      version: ${{ needs.release-please.outputs.tag_name }}
      emoji: mailbox
